### ISSUE TITLE
got 403 Forbidden error while downloading "deb" file

### ISSUE THREAD

**Issue by prashantmasuria** [erlio/docker-vernemq#50] opened 2018-05-14 18:48 UTC
We are building vernemq from the source and it is throwing error while downloading the ".deb" file.

Here is the terminal log:

```sh
Building vernemq
Step 1/20 : FROM debian:jessie
 ---> ce40fb3adcc6
Step 2/20 : MAINTAINER Erlio GmbH info@vernemq.com
 ---> Using cache
 ---> cfa0d7b2f00e
Step 3/20 : RUN apt-get update && apt-get install -y     libssl-dev     logrotate     sudo && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 8008f95469fd
Step 4/20 : ENV VERNEMQ_VERSION 1.2.2
 ---> Using cache
 ---> 901e474b901e
Step 5/20 : ADD https://bintray.com/artifact/download/erlio/vernemq/deb/jessie/vernemq_$VERNEMQ_VERSION-1_amd64.deb /tmp/vernemq.deb
ERROR: Service 'vernemq' failed to build: Got HTTP status code >= 400: 403 Forbidden
```

**Comment by prashantmasuria** [comment] 2018-05-14 19:45
@ioolkos  thank you so much for prompt reply, it will be very helpful if you can resolve this soon because this is a blocker for us.

thanks in advance

**Comment by codeadict** [comment] 2018-05-15 02:36
This is still an issue, reported at https://github.com/erlio/vernemq/issues/698

**Comment by ioolkos** [comment] 2018-05-15 08:58
The issue is resolved by bintray. Apologies (blame me: we were unaware we exceeded our storage quota) & thank you for your patience!

**Closed** 2018-05-15 13:43 UTC

**Comment by prashantmasuria** [comment] 2018-05-15 15:45
Yes, now it is working fine as earlier.

Thanks
